model:
  name: "GASIDN"
  conv_layers:
    - filters: 128
      kernel_size: 3
      stride: 1
  max_pooling:
    kernel_size: 2
  final_max_pooling:
    kernel_size: 147
  GCN_layers:
    HIDDEN_DIM :256 
    OUTPUT_DIM : 64  

training:
  batch_size: 8
  num_epochs: 60
  learning_rate: 0.0001
  optimizer: "adam"
  loss_function: "cross_entropy"
  lr_scheduler:
    step_size: 10
    gamma: 0.1

runtime:
  device: "cuda"  
  seed: 42
  log_interval: 10
  save_model: true
  output_dir: "checkpoints/"


