model:
  name: "TextCNN"
  input_size: 128
  num_classes: 10
  conv_layers:
    - filters: 64
      kernel_size: 3
      stride: 1
      padding: "same"
    - filters: 128
      kernel_size: 3
      stride: 1
      padding: "same"
  max_pooling:
    kernel_size: 2
  final_conv_layer:
    filters: 256
    kernel_size: 3
    stride: 1
    padding: "same"
  final_max_pooling:
    kernel_size: 147

training:
  batch_size: 64
  num_epochs: 50
  learning_rate: 0.001
  optimizer: "adam"
  loss_function: "cross_entropy"
  lr_scheduler:
    step_size: 10
    gamma: 0.1

runtime:
  device: "cuda"  
  seed: 42
  log_interval: 10
  save_model: true
  output_dir: "checkpoints/"


